#!/usr/bin/ruby

puts "// THIS FILE IS GENERATED BY embed_client_identity.rb"
puts "enum Environment {"
File.read(".env").each_line do |line|
  (name, value) = line.chomp.split('=').map(&:strip)
  pascal = name.split('_').collect(&:capitalize).join

  puts %Q{    static let k#{ pascal } = "#{ value }"}
end
puts "}"
