#!/usr/bin/ruby

puts "// Code generated by embed_client_identity.rb DO NOT EDIT."
puts "enum Environment {"
File.read(".env").each_line do |line|
  (name, value) = line.chomp.split('=').map(&:strip)
  pascal = name.split('_').collect(&:capitalize).join

  puts %Q{    private static let k#{ pascal } = "#{ value }"}
end
puts "}"
